run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - ineffassign
  exclusions:
    paths:
      - frontend
      - build
      - node_modules

issues:
  max-same-issues: 0
