// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function GetConfiguration():Promise<config.ResolvedConfiguration>;

export function GetConfigurations():Promise<Array<config.Configuration>>;

export function GetCurrentConfiguration():Promise<config.ResolvedConfiguration>;

export function GetOBSStatus():Promise<Record<string, any>>;

export function GetServerURL():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function LoadConfiguration(arg1:string):Promise<void>;

export function PressButton(arg1:string):Promise<void>;

export function Reconnect():Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;
