// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfiguration() {
  return window['go']['main']['App']['GetConfiguration']();
}

export function GetConfigurations() {
  return window['go']['main']['App']['GetConfigurations']();
}

export function GetCurrentConfiguration() {
  return window['go']['main']['App']['GetCurrentConfiguration']();
}

export function GetOBSStatus() {
  return window['go']['main']['App']['GetOBSStatus']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetSourceVisibility(arg1, arg2) {
  return window['go']['main']['App']['GetSourceVisibility'](arg1, arg2);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function LoadConfiguration(arg1) {
  return window['go']['main']['App']['LoadConfiguration'](arg1);
}

export function PressButton(arg1) {
  return window['go']['main']['App']['PressButton'](arg1);
}

export function Reconnect() {
  return window['go']['main']['App']['Reconnect']();
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}
