// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteButton(arg1) {
  return window['go']['main']['App']['DeleteButton'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetInputs() {
  return window['go']['main']['App']['GetInputs']();
}

export function GetScenes() {
  return window['go']['main']['App']['GetScenes']();
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function PressButton(arg1) {
  return window['go']['main']['App']['PressButton'](arg1);
}

export function SaveButton(arg1) {
  return window['go']['main']['App']['SaveButton'](arg1);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function ToggleFullscreen() {
  return window['go']['main']['App']['ToggleFullscreen']();
}

export function UpdateGrid(arg1, arg2) {
  return window['go']['main']['App']['UpdateGrid'](arg1, arg2);
}
