// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function DeleteButton(arg1:string):Promise<void>;

export function GetConfig():Promise<config.ButtonConfig>;

export function GetConfigPath():Promise<string>;

export function GetInputs():Promise<Array<string>>;

export function GetScenes():Promise<Array<string>>;

export function GetServerURL():Promise<string>;

export function GetStatus():Promise<Record<string, any>>;

export function PressButton(arg1:string):Promise<void>;

export function SaveButton(arg1:string):Promise<void>;

export function SetServerURL(arg1:string):Promise<void>;

export function ToggleFullscreen():Promise<void>;

export function UpdateGrid(arg1:number,arg2:number):Promise<void>;
