// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ConnectOBS(arg1:string,arg2:string):Promise<void>;

export function CreateButton(arg1:models.Button):Promise<void>;

export function CreateConfiguration(arg1:models.Configuration):Promise<void>;

export function DeleteButton(arg1:string):Promise<void>;

export function DeleteConfiguration(arg1:string):Promise<void>;

export function DisconnectOBS():Promise<void>;

export function ExecuteAction(arg1:models.ButtonAction):Promise<void>;

export function GetButton(arg1:string):Promise<models.Button>;

export function GetButtons():Promise<Array<models.Button>>;

export function GetConfiguration(arg1:string):Promise<models.Configuration>;

export function GetConfigurations():Promise<Array<models.Configuration>>;

export function GetDefaultConfiguration():Promise<models.Configuration>;

export function GetInputs():Promise<Array<string>>;

export function GetOBSStatus():Promise<Record<string, any>>;

export function GetSavedOBSConfig():Promise<models.OBSConfig>;

export function GetScenes():Promise<Array<string>>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetSession(arg1:string):Promise<models.ClientSession>;

export function GetSessions():Promise<Array<models.ClientSession>>;

export function ResolveConfiguration(arg1:string):Promise<models.ResolvedConfiguration>;

export function SetDefaultConfiguration(arg1:string):Promise<void>;

export function TestBinding(arg1:string):Promise<string>;

export function TestConfiguration(arg1:string):Promise<void>;

export function UpdateButton(arg1:models.Button):Promise<void>;

export function UpdateClientConfig(arg1:string,arg2:string):Promise<void>;

export function UpdateConfiguration(arg1:models.Configuration):Promise<void>;
